### ISSUE TITLE
how to remove ads?

### ISSUE THREAD

**Issue by corinloch** [alanvarghesepaul22/CINEWORLD-NextJS#12]
I locally hosted it on my ip not domain for personal use, how to remove ads, it's quite annoying when clicking on a movie and ads pops up, Thanks!

**Comment by corinloch** [comment]
Also, how to change color the hex code fde402 is quite sharp for my eyes, Thanks!

**Comment by alanvarghesepaul22** [comment]
The ads are coming from the iframe through which you watch the video content. the iframe is loaded using an api. and this api is responsible for ads. Maybe if you use any adblocker extensions you can prevent this from happening. thanks!

**Comment by alanvarghesepaul22** [comment]
Hi,
If you need to change the hex code fde402, you need to go to the
*tailwind.config.js* file and change the hex code given for *'primary*' in
the *colors* object. Providing a screen shot for you to understand. thanks!
[image: image.png]

**Comment by corinloch** [comment]
Thanks also how to remove title tag and meta on my home page, I want it to be private. Thanks!

**Comment by alanvarghesepaul22** [comment]
Sorry. I didn't understand. can you provide a screenshot of what you are
meaning to do.

**Comment by corinloch** [comment]
Nvm it's all good, one more thing how to download movies or how to add download button? is it possible? Thanks!
